### ISSUE TITLE
add a .js version in release

### ISSUE THREAD

**Issue by mirlip** [WasabiFan/cdecl-blocks-js#1]
Hi,
thanks for these additions :)
could you please add the .js version to release?

**Comment by WasabiFan** [comment]
Yeah! I can add it to the release list tomorrow morning (it's late at night my time); however, you can find a copy of the file in the repo for a project I used it in here: https://github.com/WasabiFan/vscode-cdecl/blob/master/out/cdecl.js

**Comment by mirlip** [comment]
thanks :) Do you have an example web page that would work like https://cdecl.org/ using this?

**Comment by WasabiFan** [comment]
I don't have such a page; if you are looking to test inputs/outputs, it will work exactly the same as https://cdecl.org/, so you can try things out there. If you are asking because you want a usage example, I am not 100% sure because I've only used Emscripten modules from Node.js in the past (never in-browser). You'll have to do some research on that. The part I'm unsure of is how to only invoke the `main` method when you want to, rather than immediately on page load. It might require modifying the C source and recompiling such that there is no `main` and you instead call a separate function when needed.

**Comment by mirlip** [comment]
Hi,
ok, thanks I'll have a look. My goal was to have a simple way to get cdecl.org offline in train or so.
So if you have a solution not including a browser, I'm happy with it too.

**Comment by WasabiFan** [comment]
Yeah! If your goal is just to find a way to run it locally, you can install node.js and do it like this from a terminal/command prompt (note that the dollar sign is just to signify that it's a command, don't actually type that):

```
$ node cdecl.js declare foo as int
int foo
```

You just run the JS file like that with the cdecl input passed after the file name and it will give you the output. It'll work exactly like cdecl.org.

**Comment by mirlip** [comment]
thanks for the quick solution and the release :)
